import json
import os
import time
import threading

RECORDINGS_DIR = os.path.join(os.path.dirname(__file__), "recordings")

# Only record input topics — these are the messages that drive the game.
# Output topics (sfx, mfd/present, ctrl, cards/play) are generated by
# game components in response to inputs and don't need to be recorded.
INPUT_TOPICS = {
    "gwent/cards/raw/read",
    "gwent/mfd/choose",
}

_lock = threading.Lock()
_enabled = True
_trace_file = None


def set_filename(filename: str):
    """Set the trace output filename."""
    global _trace_file
    if not filename.endswith(".jsonl"):
        filename += ".jsonl"
    _trace_file = os.path.join(RECORDINGS_DIR, filename)


def get_filepath():
    """Return the current trace file path."""
    return _trace_file


def record(topic: str, payload: str):
    """Append an input MQTT message to the trace file.

    Only records messages on INPUT_TOPICS (card reads, user choices).
    Output messages are skipped since game components regenerate them.
    """
    if not _enabled or _trace_file is None:
        return
    if topic not in INPUT_TOPICS:
        return
    entry = {
        "ts": time.time(),
        "topic": topic,
        "payload": payload,
    }
    with _lock:
        os.makedirs(RECORDINGS_DIR, exist_ok=True)
        with open(_trace_file, "a") as f:
            f.write(json.dumps(entry) + "\n")


def disable():
    """Disable tracing (used during replay to avoid re-recording)."""
    global _enabled
    _enabled = False


def enable():
    """Re-enable tracing."""
    global _enabled
    _enabled = True


def reset():
    """Clear the current trace file for a fresh recording."""
    with _lock:
        if _trace_file and os.path.exists(_trace_file):
            os.remove(_trace_file)
