
class Card(object):
    name = None

MONSTERS = {
    'name': 'Monsters',
    'starters': (
        'LEADER - Eredin - 2',
        'Clear - 1',
        'Impenetrable Fog - 1',
        'Impenetrable Fog - 2',
        'Biting Frost - 1',
        'Biting Frost - 2',
        'Torrential Rain - 1',
        'Arachas - 1',
        'Arachas - 2',
        'Arachas Behemoth',
        'Calaeno Harpy - 1',
        'Cockatrice - 1',
        'Crone-Brewess',
        'Endrega',
        'Fire Elemental - 1',
        'Forktail - 1',
        'Frightener',
        'Gargoyle',
        'Ghoul - 1',
        'Ghoul - 2',
        'Grave Hag - 1',
        'Griffin - 1',
        'Ice Giant - 1',
        'Imlerith',
        'Kayran - 1',
        'Nekker - 1',
        'Plague Maiden - 1',
        'Vampire-Garkain',
        'Werewolf - 1',
        'Wyvern',
    )
}

NILFGAARDIAN = {
    'name': 'Nilfgaardian',
    'starters': (
        'LEADER - Emyhr - 2',
        'Biting Frost - 1',
        'Biting Frost - 2',
        'Clear Weather - 1',
        'Impenetrable Fog - 1',
        'Impenetrable Fog - 2',
        'Torrential Rain - 1',
        'Assire',
        'cahir',
        'Cynthia',
        'Etolian - 1',
        'Imperal Brigade Guard - 1',
        'Imperal Brigade Guard - 2',
        'Imperal Brigade Guard - 3',
        'Nausica Cavalry - 1',
        'Nausica Cavalry - 2',
        'Rainfarn',
        'Renauld',
        'Rotten Mangonel',
        'Shilard',
        'Siege Engineer',
        'Siege Tech',
        'Stefan Skellen',
        'Tibor',
        'Vanhemar',
        'Vattier',
        'Vremde',
        'Young Emissary - 1',
        'Fire Scorpion - 1',
        'Fire Scorpion - 2',
    )
}

NORTHERN_REALMS = {
    'name': "Northern Realms",
    'starters': (
        'LEADER - Foltest - 2',
        'Clear Weather 1',
        'Impenetrable Fog - 1',
        'Impenetrable Fog - 2',
        'Biting Frost - 1',
        'Biting Frost - 2',
        'Torrential Rain - 1',
        'Ballista - 1',
        'Ballista - 2',
        'Dethmold',
        'Dun Banner Medic',
        'Kaedweni Siege Expert - 1',
        'Kaedweni Siege Expert - 2',
        'Kaedweni Siege Expert - 3',
        'Kiera Metz',
        'PFI - 1',
        'PFI - 2',
        'Phillipa',
        'Prince Stennis',
        'Redanian Foot Soldier - 1',
        'Redanian Foot Soldier - 2',
        'Sabrina',
        'Siege Tower - 1',
        'Siegfried',
        'Sile',
        'Skaggs',
        'Trebuchet - 1',
        'Trebuchet - 2',
        'Ves',
        'Yarpen Zigrin',
    )
}

SCOIATAEL = {
    'name': "Scoia'tael",
    'starters': (
        'LEADER - Francesca - 2',
        'Clear Weather 1',
        'Impenetrable Fog - 1',
        'Impenetrable Fog - 2',
        'Biting Frost - 1',
        'Biting Frost - 2',
        'Torrential Rain - 1',
        'CiaranaepEasnilie',
        'Dennis Crammer',
        'Dol Blathanna Archer - 1',
        'Dol Blathanna Scout - 1',
        'Dol Blathanna Scout - 2',
        'Dwarven Skirmisher - 1',
        'Dwarven Skirmisher - 2',
        'Dwarven Skirmisher - 3',
        'Elven Skirmisher - 1',
        'Elven Skirmisher - 2',
        'Filavandrelaen Fidhail',
        'Havekar Healer - 1',
        'Havekar Smuggler - 1',
        'Ida',
        'Iorveth',
        'Mahakaman Defender - 1',
        'Mahakaman Defender - 2',
        'Mahakaman Defender - 3',
        'Riordain',
        'Toruviel',
        'Vrihedd Brigade Recruit',
        'Vrihedd Brigade Veteran - 1',
        'Vrihedd Brigade Veteran - 2',
    )
}

SKELLIGE = {
    'name': 'Skellige',
    'starters': (
        'LEADER - Crach - 2',
        'Clear Weather 1',
        'Impenetrable Fog - 1',
        'Impenetrable Fog - 2',
        'Biting Frost - 1',
        'Biting Frost - 2',
        'Torrential Rain - 1',
        'Berserker',
        'Birna',
        'Blueboy Lugos',
        'Clan an Craite - 1',
        'Clan an Craite - 2',
        'Clan an Craite - 3',
        'Clan Brokvar Archer',
        'Clan Brokvar Archer',
        'Clan Drummond Shield Maiden - 1',
        'Clan Heymaey Skald',
        'Clan Tordarroch Armorsmith',
        'Donar',
        'Hjalmar',
        'Holger Blackhand',
        'Light LongShip - 1',
        'Light LongShip - 2',
        'Madman Lugos',
        'Mardroeme - 1',
        'Svanrige',
        'Vildkarl',
        'Young Vildkarl - 1',
        'Udalryk',
        'War Longship - 1',
        'War Longship - 2',
        'Young Berserker - 1',
    )
}

ALL_FACTIONS = [NORTHERN_REALMS, NILFGAARDIAN, SKELLIGE, SCOIATAEL, MONSTERS]
